spring.application.name=ProyectoValenRuta
#modo de conexion a la bd => driver mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#conexion a la url
spring.datasource.url=jdbc:mysql://localhost:3306/proyectovalenruta
#definir user y pass
spring.datasource.username=root
spring.datasource.password=root
#actualiza la BD
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
#peticiones mysql en consola
spring.jpa.show-sql=true
#endpoint
server.address=0.0.0.0
server.port=8080

jwt.secret=MI_CLAVE_SECRETA_SUPER_LARGA_DE_32_CARACTERES_MINIMO_1234567890

jwt.expiration=86400000

google.maps.api.key=AIzaSyAIHBFj_6F2oIRl34c20B3K-O_DTTg99S8

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs